repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Non-modifying hooks
      - id: check-added-large-files
        exclude: ^(docs/|data/charts/).*
      - id: check-yaml
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
        # Modifying hooks
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
        exclude: ^docs/
      - id: trailing-whitespace
        exclude: ^docs/|\.md$
  - repo: https://github.com/google/yamlfmt
    rev: v0.14.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.29.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
      - id: ruff
        name: ruff isort
        args: [--fix, --select=I, --show-fixes, --config=pyproject.toml]
      - id: ruff
        name: ruff check
        args: [--fix, --config=pyproject.toml]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        name: Run mypy
        exclude: ^adder/tests/
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        name: Strip Jupyter notebook output (nbstripout)
        files: \.ipynb$
        # Keep last to ensure formatting happens after all other fixes
  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black
        exclude: ^docs/
      - id: black-jupyter
exclude: ^(.md|.svn|CVS|.bzr|.hg|.git|__pycache__|.tox|.ipynb_checkpoints|assets|tests/assets/)
